### ISSUE TITLE
Fragment doesn't work when following Link, but works when loading the URL directly

### ISSUE THREAD

**Issue by MatthewPikar** [FormidableLabs/redux-little-router#171]
I'm trying to configure two fragments, but they do not work consistently between being loaded directly and through Link/dispatch.  I could use some help in figuring out what is happening here.

So I have these Fragments:
```
<Fragment forRoutes={[root + '/trips', root + '/trips/:trip', root + '/trips/:trip/actions/:action']} >
    <TripCardStack />
</Fragment>
<Fragment forRoute={ root + '/trips/:trip/actions/:action'} >
    <ActionCard />
</Fragment>
```
The first Fragment loads without a problem.
The second Fragment only loads when loading the route directly from the url (ie: /trips/13652768979/actions/2457248283).  
The second Fragment does not work when I dispatch/follow a Link component, which contains exact same url.  
When I do load the url directly and then navigate to '/trips', the second Fragment loads regardless.

The reducer executes in both cases and updates the route state correctly.

Route state when loading directly:
```
params: 
  action: "2457248283"
  trip: "13652768979"
  pathname: "/trips/13652768979/actions/2457248283"
  query: 
    No Properties
  result: 
    parent: 
      parent: 
        route: "/trips/:trip/actions"
        title: "Actions"
      title: "Action"
  route :"/trips/:trip/actions/:action"
  search : ""
```

Route state when loading through Link dispatch:
```
hash: ""
key: "0esdap"
options:
  persistQuery: undefined
params: 
  action: "2457248283"
  trip: "13652768979"
pathname: "/trips/13652768979/actions/2457248283"
previous: Object
query:
  No Properties
result:
  parent: Object
  title: "Action"
route: "/trips/:trip/actions/:action"
search: ""
state: Object
```

Using: 
    "react": "^15.4.2",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-little-router": "^13.1.2",
    "redux-saga": "^0.15.3",
